// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	http "net/http"

	bmcspidernetiov1beta1 "github.com/spidernet-io/bmc/pkg/k8s/apis/bmc.spidernet.io/v1beta1"
	scheme "github.com/spidernet-io/bmc/pkg/k8s/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type BmcV1beta1Interface interface {
	RESTClient() rest.Interface
	ClusterAgentsGetter
	HostEndpointsGetter
	HostOperationsGetter
	HostStatusesGetter
}

// BmcV1beta1Client is used to interact with features provided by the bmc.spidernet.io group.
type BmcV1beta1Client struct {
	restClient rest.Interface
}

func (c *BmcV1beta1Client) ClusterAgents() ClusterAgentInterface {
	return newClusterAgents(c)
}

func (c *BmcV1beta1Client) HostEndpoints() HostEndpointInterface {
	return newHostEndpoints(c)
}

func (c *BmcV1beta1Client) HostOperations() HostOperationInterface {
	return newHostOperations(c)
}

func (c *BmcV1beta1Client) HostStatuses() HostStatusInterface {
	return newHostStatuses(c)
}

// NewForConfig creates a new BmcV1beta1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*BmcV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new BmcV1beta1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*BmcV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &BmcV1beta1Client{client}, nil
}

// NewForConfigOrDie creates a new BmcV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *BmcV1beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new BmcV1beta1Client for the given RESTClient.
func New(c rest.Interface) *BmcV1beta1Client {
	return &BmcV1beta1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := bmcspidernetiov1beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *BmcV1beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
