// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type ClusterAgentExpansion interface{}

type HostEndpointExpansion interface{}
