apiVersion: "bmc.spidernet.io/v1beta1"
kind: "ClusterAgent"
metadata:
  name: "{{ .Release.Name }}-clusteragent"
  labels:
    {{- include "bmc-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  agentYaml:
    replicas: {{ .Values.clusterAgent.agentYaml.replicas }}
    image: "{{ .Values.clusterAgent.agentYaml.image.repository }}:{{ default .Chart.Version .Values.clusterAgent.agentYaml.image.tag }}"
    underlayInterface: "{{ .Values.clusterAgent.agentYaml.underlayInterface }}"
