apiVersion: "bmc.spidernet.io/v1beta1"
kind: "ClusterAgent"
metadata:
  name: "{{ .Release.Name }}-clusteragent"
  labels:
    {{- include "bmc-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  agentYaml:
    replicas: {{ .Values.clusterAgent.agentYaml.replicas }}
    image: "{{ .Values.clusterAgent.agentYaml.image.repository }}:{{ default .Chart.Version .Values.clusterAgent.agentYaml.image.tag }}"
    underlayInterface: "{{ .Values.clusterAgent.agentYaml.underlayInterface }}"
    {{- with .Values.clusterAgent.agentYaml.nodeAffinity }}
    nodeAffinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.clusterAgent.agentYaml.nodeName }}
    nodeName: {{ .Values.clusterAgent.agentYaml.nodeName }}
    {{- end }}
  {{- with .Values.clusterAgent.endpoint }}
  endpoint:
    port: {{ .port }}
    https: {{ .https }}
    {{- if .secretName }}
    secretName: {{ .secretName }}
    {{- end }}
    {{- if .secretNamespace }}
    secretNamespace: {{ .secretNamespace }}
    {{- end }}
  {{- end }}
  {{- with .Values.clusterAgent.feature }}
  feature:
    enableDhcpServer: {{ .enableDhcpServer }}
    enableDhcpDiscovery: {{ .enableDhcpDiscovery }}
    dhcpServerInterface: {{ .dhcpServerInterface }}
    redfishMetrics: {{ .redfishMetrics }}
    enableGuiProxy: {{ .enableGuiProxy }}
  {{- end }}
