apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bmcservers.bmc.spidernet.io
spec:
  group: bmc.spidernet.io
  names:
    kind: BMCServer
    listKind: BMCServerList
    plural: bmcservers
    singular: bmcserver
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - host
                - username
                - password
              properties:
                host:
                  type: string
                username:
                  type: string
                password:
                  type: string
            status:
              type: object
              properties:
                connected:
                  type: boolean
                lastConnected:
                  type: string
                  format: date-time
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusteragents.bmc.spidernet.io
spec:
  group: bmc.spidernet.io
  names:
    kind: ClusterAgent
    listKind: ClusterAgentList
    plural: clusteragents
    singular: clusteragent
  scope: Cluster
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
                readyReplicas:
                  type: integer
