apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bmcservers.bmc.io
spec:
  group: bmc.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                interface:
                  type: string
                clusterName:
                  type: string
  scope: Namespaced
  names:
    plural: bmcservers
    singular: bmcserver
    kind: BmcServer
    shortNames:
    - bmc
