apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dhcp-config
  labels:
    {{- include "bmc-operator.labels" . | nindent 4 }}
data:
  dhcp-config.tmpl: |
    # 30 days
    default-lease-time 2592000;
    # 30 days
    max-lease-time 2592000;
    subnet {{ "{{ .Subnet }}" }} netmask {{ "{{ .Netmask }}" }} {
        range {{ "{{ .Range }}" }};
        option routers {{ "{{ .Router }}" }};
        option subnet-mask {{ "{{ .SubnetMask }}" }};
    }
