apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bmc-operator.fullname" . }}
  labels:
    {{- include "bmc-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  - endpoints
  - events
  - persistentvolumeclaims
  verbs:
  - "*"
- apiGroups:
  - bmc.spidernet.io
  resources:
  - bmcservers
  - clusteragents
  - bmcservers/status
  - clusteragents/status
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    {{- include "bmc-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["bmc.spidernet.io"]
  resources: ["clusteragents"]
  verbs: ["*"]
- apiGroups: ["bmc.spidernet.io"]
  resources: ["clusteragents/status"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bmc-operator.fullname" . }}
  labels:
    {{- include "bmc-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bmc-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "bmc-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    {{- include "bmc-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-operator
subjects:
- kind: ServiceAccount
  name: {{ include "bmc-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
