// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/spidernet-io/bmc/pkg/k8s/apis/bmc.spidernet.io/v1beta1"
	bmcspidernetiov1beta1 "github.com/spidernet-io/bmc/pkg/k8s/client/clientset/versioned/typed/bmc.spidernet.io/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeHostEndpoints implements HostEndpointInterface
type fakeHostEndpoints struct {
	*gentype.FakeClientWithList[*v1beta1.HostEndpoint, *v1beta1.HostEndpointList]
	Fake *FakeBmcV1beta1
}

func newFakeHostEndpoints(fake *FakeBmcV1beta1) bmcspidernetiov1beta1.HostEndpointInterface {
	return &fakeHostEndpoints{
		gentype.NewFakeClientWithList[*v1beta1.HostEndpoint, *v1beta1.HostEndpointList](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("hostendpoints"),
			v1beta1.SchemeGroupVersion.WithKind("HostEndpoint"),
			func() *v1beta1.HostEndpoint { return &v1beta1.HostEndpoint{} },
			func() *v1beta1.HostEndpointList { return &v1beta1.HostEndpointList{} },
			func(dst, src *v1beta1.HostEndpointList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.HostEndpointList) []*v1beta1.HostEndpoint {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.HostEndpointList, items []*v1beta1.HostEndpoint) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
