// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/spidernet-io/bmc/pkg/k8s/apis/bmc.spidernet.io/v1beta1"
	bmcspidernetiov1beta1 "github.com/spidernet-io/bmc/pkg/k8s/client/clientset/versioned/typed/bmc.spidernet.io/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterAgents implements ClusterAgentInterface
type fakeClusterAgents struct {
	*gentype.FakeClientWithList[*v1beta1.ClusterAgent, *v1beta1.ClusterAgentList]
	Fake *FakeBmcV1beta1
}

func newFakeClusterAgents(fake *FakeBmcV1beta1) bmcspidernetiov1beta1.ClusterAgentInterface {
	return &fakeClusterAgents{
		gentype.NewFakeClientWithList[*v1beta1.ClusterAgent, *v1beta1.ClusterAgentList](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("clusteragents"),
			v1beta1.SchemeGroupVersion.WithKind("ClusterAgent"),
			func() *v1beta1.ClusterAgent { return &v1beta1.ClusterAgent{} },
			func() *v1beta1.ClusterAgentList { return &v1beta1.ClusterAgentList{} },
			func(dst, src *v1beta1.ClusterAgentList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.ClusterAgentList) []*v1beta1.ClusterAgent {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.ClusterAgentList, items []*v1beta1.ClusterAgent) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
