// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/spidernet-io/bmc/pkg/k8s/client/clientset/versioned/typed/bmc.spidernet.io/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeBmcV1beta1 struct {
	*testing.Fake
}

func (c *FakeBmcV1beta1) ClusterAgents() v1beta1.ClusterAgentInterface {
	return newFakeClusterAgents(c)
}

func (c *FakeBmcV1beta1) HostEndpoints() v1beta1.HostEndpointInterface {
	return newFakeHostEndpoints(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeBmcV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
