// Package dhcpserver provides DHCP server management functionality.
package dhcpserver

const (
	// DhcpConfigPath is the path to the DHCP server configuration file.
	// This file is generated by the package and used by the dhcpd daemon.
	DhcpConfigPath = "/etc/dhcp/dhcpd.conf"

	// DhcpLeaseFileFormat is the format string for DHCP lease file path
	DhcpLeaseFileFormat = "/var/lib/dhcp/%s-dhcpd.leases"

	// DhcpLogFile is the path to the DHCP server log file.
	// This file contains operational logs from the DHCP server.
	DhcpLogFile = "/var/log/dhcpd.log"

	// DhcpBinary is the name of the ISC DHCP server daemon executable.
	// The package expects this binary to be available in the system PATH.
	DhcpBinary = "dhcpd"

	// DhcpConfigTemplatePath is the path to the DHCP server configuration template file.
	DhcpConfigTemplatePath = "/etc/dhcp/templates/dhcp-config.tmpl"

	// MonitorInterval is the interval in seconds for monitoring the DHCP server.
	// The monitor routine checks server health and updates statistics at this interval.
	MonitorInterval = 30 // seconds

	// EnvDhcpDebugLog is the environment variable name that controls whether dhcpd's
	// output should be logged to stdout/stderr. When set to "true", all dhcpd output
	// will be captured and logged through the BMC logging system.
	//EnvDhcpDebugLog = "DHCP_DEBUG_LOG"
)
