// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// ClusterAgentListerExpansion allows custom methods to be added to
// ClusterAgentLister.
type ClusterAgentListerExpansion interface{}

// HostEndpointListerExpansion allows custom methods to be added to
// HostEndpointLister.
type HostEndpointListerExpansion interface{}
