// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	bmcspidernetiov1beta1 "github.com/spidernet-io/bmc/pkg/k8s/apis/bmc.spidernet.io/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HostEndpointLister helps list HostEndpoints.
// All objects returned here must be treated as read-only.
type HostEndpointLister interface {
	// List lists all HostEndpoints in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*bmcspidernetiov1beta1.HostEndpoint, err error)
	// Get retrieves the HostEndpoint from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*bmcspidernetiov1beta1.HostEndpoint, error)
	HostEndpointListerExpansion
}

// hostEndpointLister implements the HostEndpointLister interface.
type hostEndpointLister struct {
	listers.ResourceIndexer[*bmcspidernetiov1beta1.HostEndpoint]
}

// NewHostEndpointLister returns a new HostEndpointLister.
func NewHostEndpointLister(indexer cache.Indexer) HostEndpointLister {
	return &hostEndpointLister{listers.New[*bmcspidernetiov1beta1.HostEndpoint](indexer, bmcspidernetiov1beta1.Resource("hostendpoint"))}
}
