// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	bmcspidernetiov1beta1 "github.com/spidernet-io/bmc/pkg/k8s/apis/bmc.spidernet.io/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HostStatusLister helps list HostStatuses.
// All objects returned here must be treated as read-only.
type HostStatusLister interface {
	// List lists all HostStatuses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*bmcspidernetiov1beta1.HostStatus, err error)
	// Get retrieves the HostStatus from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*bmcspidernetiov1beta1.HostStatus, error)
	HostStatusListerExpansion
}

// hostStatusLister implements the HostStatusLister interface.
type hostStatusLister struct {
	listers.ResourceIndexer[*bmcspidernetiov1beta1.HostStatus]
}

// NewHostStatusLister returns a new HostStatusLister.
func NewHostStatusLister(indexer cache.Indexer) HostStatusLister {
	return &hostStatusLister{listers.New[*bmcspidernetiov1beta1.HostStatus](indexer, bmcspidernetiov1beta1.Resource("hoststatus"))}
}
