// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	bmcspidernetiov1beta1 "github.com/spidernet-io/bmc/pkg/k8s/apis/bmc.spidernet.io/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HostOperationLister helps list HostOperations.
// All objects returned here must be treated as read-only.
type HostOperationLister interface {
	// List lists all HostOperations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*bmcspidernetiov1beta1.HostOperation, err error)
	// Get retrieves the HostOperation from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*bmcspidernetiov1beta1.HostOperation, error)
	HostOperationListerExpansion
}

// hostOperationLister implements the HostOperationLister interface.
type hostOperationLister struct {
	listers.ResourceIndexer[*bmcspidernetiov1beta1.HostOperation]
}

// NewHostOperationLister returns a new HostOperationLister.
func NewHostOperationLister(indexer cache.Indexer) HostOperationLister {
	return &hostOperationLister{listers.New[*bmcspidernetiov1beta1.HostOperation](indexer, bmcspidernetiov1beta1.Resource("hostoperation"))}
}
