apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusteragents.bmc.spidernet.io
spec:
  group: bmc.spidernet.io
  names:
    kind: ClusterAgent
    listKind: ClusterAgentList
    plural: clusteragents
    singular: clusteragent
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: ClusterAgent is the Schema for the clusteragents API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest internal
              value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object
              represents. Servers may infer this from the endpoint the client submits
              requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterAgentSpec defines the desired state of ClusterAgent
            properties:
              agentYaml:
                description: AgentConfig defines the configuration for the agent
                type: object
                properties:
                  image:
                    description: Image is the agent container image
                    type: string
                  replicas:
                    description: Replicas is the number of agents to run
                    type: integer
                    default: 1
                    minimum: 0
                  underlayInterface:
                    description: UnderlayInterface specifies the network interface configuration for underlay network
                    type: string
                required:
                - underlayInterface
            required:
            - agentYaml
            type: object
          status:
            description: ClusterAgentStatus defines the observed state of ClusterAgent
            properties:
              ready:
                description: Whether the agent is ready
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    additionalPrinterColumns:
    - name: READY
      type: boolean
      jsonPath: .status.ready
    - name: AGE
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
