apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusteragents.bmc.spidernet.io
spec:
  group: bmc.spidernet.io
  names:
    kind: ClusterAgent
    listKind: ClusterAgentList
    plural: clusteragents
    singular: clusteragent
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: ClusterAgent is the Schema for the clusteragents API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest internal
              value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object
              represents. Servers may infer this from the endpoint the client submits
              requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterAgentSpec defines the desired state of ClusterAgent
            properties:
              image:
                description: Image is the agent container image
                type: string
              replicas:
                description: Replicas is the number of agents to run
                type: integer
              clusterName:
                description: Name of the cluster
                type: string
              interface:
                description: Network interface to use
                type: string
            required:
            - image
            - replicas
            - clusterName
            - interface
            type: object
          status:
            description: ClusterAgentStatus defines the observed state of ClusterAgent
            properties:
              availableReplicas:
                description: AvailableReplicas is the number of agents currently running
                type: integer
              lastUpdated:
                description: LastUpdated is the last time the status was updated
                format: date-time
                type: string
              allocatedIPCount:
                description: Number of allocated IPs
                type: integer
              totalIPCount:
                description: Total number of IPs
                type: integer
              allocatedIPs:
                description: List of allocated IPs
                items:
                  type: string
                type: array
              ready:
                description: Whether the agent is ready
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
