name: Build Image Release

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions: write-all

jobs:
  call-workflow:
    uses: ./.github/workflows/call-build-image.yaml
    with:
      ref: ${{ inputs.ref }}
      push: "true"
      upload: "false"
    secrets: inherit
